version: '3.8'

services:
  app:
    build: .
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
    env_file:
      - backend/.env.production
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: